services:

  nginx:
    build: ./app
    container_name: perf-nginx
    ports:
      - "8080:80"

  jmeter:
    image: justb4/jmeter:latest
    container_name: perf-jmeter
    depends_on:
      - nginx
    volumes:
      - ./jmeter:/tests
      - ./reports:/results
    entrypoint: >
      sh -c "
      sleep 10 &&
      jmeter -n
      -t /tests/Eph_Per_Local.jmx
      -l /results/results.jtl
      -e
      -o /results/report
      "